### ISSUE TITLE
Add 3 ways to interact with discord bot

### ISSUE THREAD

**Issue by FLEYreal** [StormShop/ChatGPT-Assistant#4]
3 Ways to interact with chatGPT in discord server

- [x] /command <Message>
- [x] @ping <Message>
- [x] DM the bot

**Comment by seyLu** [comment]
DM impl currently blocked. Cannot receive events when dming bot. Probably permission issues on the bot side (not allowed to read dms, etc.).

**Comment by seyLu** [comment]
Solved the permission issue via new bot. Also finished DM impl.

**Comment by seyLu** [comment]
Can you approve the [PR](https://github.com/StormShop/ChatGPT-Assistant/pull/8). TY.

**Comment by seyLu** [comment]
Done
